/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.18
 * Generated at: 2016-11-04 06:42:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.usercontrol;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.opensymphony.xwork2.util.ValueStack;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.2.jar", Long.valueOf(1476156103713L));
    _jspx_dependants.put("jar:file:/F:/gitPath/WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/egou-search/WEB-INF/lib/struts2-core-2.5.2.jar!/META-INF/struts-tags.tld", Long.valueOf(1467859878000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.opensymphony.xwork2.util.ValueStack");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String a = request.getParameter("step");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/statics/css/footer.css\" />\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"blank\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"foot fl\">\r\n");
      out.write("\t\t<div class=\"wdwrap\">\r\n");
      out.write("\t\t\t<ul class=\"foot-text\">\r\n");
      out.write("\t\t\t\t<li><span>Copyright © 2012深圳市云商微店网络技术有限公司</span><span>地址：深圳市罗湖区国威路68号互联网产业园2栋5层</span></li>\r\n");
      out.write("\t\t\t\t<li><span>电话：0755-25679988</span> <span>传真：0755-23910940</span> <span>E-mail：<a href=\"mailto:kefu@okwei.com\" title=\"E-mail\">kefu@okwei.com</a></span></li>\r\n");
      out.write("\t\t\t\t<li><span>经营许可证：粤ICP备<a href=\"http://www.okwei.com/aboutus.html#sz\" title=\"经营许可证\" target=\"_blank\" style=\"text-decoration: underline;\">10203293号-3</a></span> <span>增值电信业务经营许可证：<a href=\"http://www.okwei.com/aboutus.html#dxzzfw\" title=\"增值电信业务经营许可证\" target=\"_blank\" style=\"text-decoration: underline;\">粤B2-20130803</a></span></li>\r\n");
      out.write("\t\t\t\t<li><a target=\"_blank\" title=\"法律顾问\">法律顾问：广东德盈律师事务所 欧雄灿</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<p class=\"foot-pic\">\r\n");
      out.write("\t\t\t\t<a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#sz\" title=\"营业执照\"><img alt=\"营业执照\" src=\"http://base1.okwei.com/statics/images/foot1.png\"></a> <a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#sz\" title=\"税务登记\"><img alt=\"税务登记\" src=\"http://base1.okwei.com/statics/images/foot2.png\"></a> <a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#kxrz\" title=\"工商网监\"><img alt=\"工商网监\" src=\"http://base1.okwei.com/statics/images/foot3.png\"></a> <a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#kxrz\" title=\"众信网络身份现场认证\"><img alt=\"众信网络身份现场认证\" src=\"http://base1.okwei.com/statics/images/foot4.png\"></a> <a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#kxrz\"\r\n");
      out.write("\t\t\t\t\ttitle=\"可信网站认证\"><img alt=\"可信网站认证\" src=\"http://base1.okwei.com/statics/images/foot5.png\"></a> <a target=\"_blank\" href=\"http://www.okwei.com/aboutus.html#dxzzfw\" title=\"电信增值服务许可证\"><img alt=\"电信增值服务许可证\" src=\"http://base1.okwei.com/statics/images/foot6.png\"></a> <a target=\"_blank\" href=\"javascript:void(0);\" title=\"财付通特约商户\"><img alt=\"财付通特约商户\" src=\"http://base1.okwei.com/statics/images/foot7-1.png\"></a> <a target=\"_blank\" href=\"javascript:void(0);\" title=\"银联特约商户\"><img alt=\"银联特约商户\" src=\"http://base1.okwei.com/statics/images/foot8-1.png\"></a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
